# Generated by Django 5.1.6 on 2025-02-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('nebulosa', 'Nebulosa'), ('estrela', 'Estrela'), ('planeta', 'Planeta'), ('galaxia', 'Galáxia')], default='', max_length=100),
        ),
    ]
